version: '2'
services:
  web:
    image: step_6
    ports:
      - "8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=docker-kata
      - POSTGRES_USER=docker-kata
